import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import { SidebarProvider } from "@/component/providers/SidebarProvider";
import Footer from "@/component/Footer";
import Sidebar from "@/component/Sidebar";
import Auth from "@/component/auth/Auth";
import MainContent from "@/component/MainConent";
import Bottombar from "@/component/Bottombar";

const montserrat = Montserrat({
  subsets: ['latin'], // Specify the character subsets you need
  weight: ['400', '700'], // Define the weights you want to use
  variable: '--font-montserrat', // Optional: Define a CSS variable for easier use with Tailwind CSS
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className}  antialiased`}
      >
        <SidebarProvider>
          {/* <Auth /> */}
          <Header />
          <main className="flex pt-14 relative bg-[#111923]">
            <Sidebar />
            <div className="main-content">
              <MainContent />
              {children}
              <Footer />
            </div>
          </main>
          <Bottombar />
          <Auth />
        </SidebarProvider>
      </body>
    </html>
  );
}
